logging:
  level: info

listenPort: 10000

cache:
  redis:
    enabled: true
    host: "localhost"
    port: 6379
    db: 0
    expirationTime: 600s
  bigCache:
    enabled: true
    shards: 1024
    maxEntriesInWindow: 2048
    maxEntrySize: 512
    hardMaxCacheSize: 4096
    verbose: true

database:
  write:
    host: "localhost"
    database: "postgres"
    port: 5432
    timezone: "Asia/Tehran"
  read:
    host: "localhost"
    database: "postgres"
    port: 5432
    timezone: "Asia/Tehran"

sentry:
  dsn: ""

health-check:
  enabled: true

prometheus:
  enabled: true
  addr: "0.0.0.0:31775"
