apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: userProfile
  name: userProfile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userProfile
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
