apiVersion: v1
kind: Service
metadata:
  name: userProfile
  labels:
    name: userProfile
spec:
  ports:
    - name: grpc
      port: 10000
      targetPort: 10000
    - name: prometheus
      protocol: TCP
      port: 31775
      targetPort: 31775
  selector:
    app: userProfile
